### PR TITLE
Add timeout support.

### PR DESCRIPTION
**Pull request by ceilfors**
Trying to resolve issue #57.

### CODE REVIEW

**Comment by jamezp** [comment]
We require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to the these terms?

**Comment by ceilfors** [comment]
Yes.

**Comment by jamezp** [comment]
Thanks! Merged

**Comment by ceilfors** [comment]
Do you have any release schedule? Currently I'm using my hacked version of the plugin. Would be great if I can use the released version of this plugin.

**Comment by jamezp** [comment]
I'm working on getting a release out this week. Hopefully today or tomorrow.

**Comment by ceilfors** [comment]
Great. Thanks! :beer:

**Comment by jamezp** [comment]
7.7.Final has been released.

**Comment by mattdrees** [comment]
Thanks James! Been waiting for that.

**Comment by ceilfors** [comment]
@jamezp That's fast. Thanks!

**Pull request closed without merging**
